### PR TITLE
Implementation of input intermediate

### PR DESCRIPTION
**Pull request by zrock-dev**
# Task-207 Implementation of Input intermediate

https://tree.taiga.io/project/joseluis-teran-coffeetime/task/207

## Description

- #### What did I do?
Following the[ architecture update](https://github.com/Pending-Name-21/arquitecture/pull/17), the client socket component has been migrated to the bridge.

Implemented Events un-marshalling 

#### How did I do it?
- Added implementation documentation.

- Updated CI to ignore CoffeeTime (machine-generated code).

- Implemented event buffers:
  - Receiver now populates a thread-safe LIFO collection with deserialized client data.
  - Refactored Receiver to handle ByteBuffer, with SocketServer managing the socket.

- Added FlatBuffer communication protocol:
  - FlatBuffer is an efficient serialization library.
  - KeyboardEvents are generated on user input and deserialized using FlatBuffer.

- Created SocketServer:
  - A Runnable that processes client data with the Receiver feeding the buffers.

#### Why did I do it?
  To improve maintainability, enhance functionality with new features, and streamline exception handling and testing.

## Testing Instructions
Remove the Disabled line from bridge/src/test/java/com/bridge/ipc/SocketServerTest.java
Execute:
`$ ./gradlew test --tests com.bridge.ipc.SocketServerTest#startServer`

Open another terminal, and checkout the branch [spike-xx/serialization](https://github.com/Pending-Name-21/screen/tree/spike-xx/serialization) (It's from the screen repo)
Then execute 
`$ cargo --quiet test send_flattbuf`

You should see something like this.
image

## Type of Change

Put an `x` in all the boxes that apply:

- [x] ✨ New Feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug Fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking Change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code Refactor
- [ ] ✅ Build Configuration Change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

## Pull Request Checklist

- [x] My commit messages are detailed.
- [x] My code follows the code style of this project.
- [ ] No existing features have been broken without good reason.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by zrock-dev** [comment]
This PR it's a migration and refactor of 
https://github.com/Pending-Name-21/miscellany/pull/2

**Comment by luiggy-mamani-jalafund** [comment]
Please, add the mouse events that will come from the screen

**Review by codeFactory12 — APPROVED** [review]

**Comment by zrock-dev** [comment]
> Please, add the mouse events that will come from the screen

Here's the draft implementation I'll implement that draft on this PR.
https://github.com/Pending-Name-21/miscellany/pull/18

**Review by codeFactory12 — APPROVED** [review]
Approved

Screenshot from 2024-06-27 14-46-04

**Review by luiggy-mamani-jalafund — APPROVED** [review]

**Pull request merged**
